ClusterLoader:
  delete: true
  projects:
    - num: 1
      basename: clusterproject
      tuning: default
      templates:
        - num: 10
          image: k8s.gcr.io/pause-amd64:3.0
          basename: echo
          file: cronjob-echo.yaml
  tuningsets:
    - name: default
      pods:
        stepping:
          stepsize: 10
          pause: 30s
        ratelimit:
          delay: 100ms
