apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: echo-${IDENTIFIER}
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            job: echo-${IDENTIFIER}
        spec:
          containers:
          - name: echo
            image: busybox
            command: ["/bin/sh",  "-c", "date; echo Hello from the Kubernetes cluster"]
          restartPolicy: Never
